FROM python:3.10-slim
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY ../django_app/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY ../django_app /app
CMD ["gunicorn", "django_app.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
